### ISSUE TITLE
Change of the test approach - splicing-of-wave-program-with-baseline-constraints__splice_main_splice_ad

### ISSUE THREAD

**Issue by Lis-TV** [cta-wave/dpctf-tests#107]
After switch to splice_ad the timecodes starts from 0, then after reaching end there is discontinuity in the displayed timecodes.
Propose use content with timecodes adjusted to expected play position, smoothly increasing. 
Content from splice_ad should display timecode from the beginning of the 4th segment (5.76s). Propose also adjust display of timecodes in splice_main for segment 4th and 5th,

**Comment by Lis-TV** [comment]
Please correct me if I miss something.
The playout (main) starts from 0 as well as the timecodes in the video. The 'currentTime' (both as a number an timecode) is matching to timecodes in the video. 
Then at switch time the add is played, and the timecodes are again starting from 0 but the  'currentTime' is continuing. So there is mismatch between timecodes burn in video and currentTime. Is it handled by test harness?
Also, the test description is 
"The expectation is that the device plays back these splices seamlessly."
How do you detect if the video is seamless (for example no freezing/missing frames/black frames) if the content changes rapidly between main and add?

**Comment by yanj-github** [comment]
Hi @Lis-TV, from device observation framework:
Any missing frames from main to ad then ad to main is getting caught by "every frame is rendered" observation. So, the observation will fail is there is any missing frames and those missing frame numbers are reported. 
In terms of freezing and black frames, it will cause the playback duration observation to fail, as there will be a short delay caused by freezing and black frames if there is any. Also, the current time match observation to fail as well.

re;
> Then at switch time the add is played, and the timecodes are again starting from 0 but the 'currentTime' is continuing. So, there is mismatch between timecodes burn in video and currentTime. Is it handled by test harness?

This is handled in observation framework when content changes, "timecodes burn in video and currentTime" is adjusted by expected duration before the splice of previous content, then it compared with timecodes.

**Comment by Lis-TV** [comment]
Seems the observation framework handles it.
