### ISSUE TITLE
Duration names changed in tests.json generated file

### ISSUE THREAD

**Issue by andyburras** [cta-wave/dpctf-tests#37]
It looks like the generation process has altered the names of "cmaf_track_duration" and "fragment_duration".
This breaks the Observation Framework which relies on reading named parameters from the JSON.

**Comment by FritzHeiden** [comment]
@andyburras I changed them back to the previous names. Feel free to close this issue

**Comment by andyburras** [comment]
Thanks @FritzHeiden . If we need to, we can amend things, but we do need to try to coordinate any changes to the JSON structure to keep everything in step.

**Comment by louaybassbouss** [comment]
> Thanks @FritzHeiden . If we need to, we can amend things, but we do need to try to coordinate any changes to the JSON structure to keep everything in step.

@andyburras yes fully agree any changes to APIs, JSON Structure or filenames will be documented  and communicated to you. We will use also tags for new version so that you can easily continue testing with a stable version (the [dpctf-deploy](https://github.com/cta-wave/dpctf-deploy#create-image) project allows you  to create the docker image with a dedicated version (e.g. using commitId) of test runner and tests project).
