### ISSUE TITLE
directory name in the generated folder

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-tests#5]
It was agreed in the November 30th test runner call that the directory name in the generated folder would not be the MD5 hash but would be the concatenation of the code filename, the video filename & the audio filename. The tool that processes the .csv file and generates tests.json can check for uniqueness & append a "-1" or "-2" if any combination would not be unique in the scope of a single run.

**Comment by jpiesing** [comment]
@louaybassbouss Please close this issue when it's implemented and tested.

**Comment by louaybassbouss** [comment]
@FritzHeiden we decided in todays call to use human-readable names for the generated files. Example: 

For the following generated test 

```
"a83623b5d253a8e3e44954144e64f3d4": {
         "path": "Folder1/a83623b5d253a8e3e44954144e64f3d4.html",
         "video": "http://dash.akamaized.net/WAVE/ContentModel/SinglePeriod/Fragmented/ToS_MultiRate_fragmented.mpd",
         "audio": "https://dash.akamaized.net/WAVE/ContentModel/SinglePeriod/Fragmented/ToS_HEAACv2_fragmented.mpd",
         "code": "fullscreen-playback-of-switching-sets-manual.html"
 },
``` 
use filename `fullscreen-playback-of-switching-sets-manual-ToS_MultiRate_fragmented-ToS_HEAACv2_fragmented.html` instead of `a83623b5d253a8e3e44954144e64f3d4.html`. If there are file name conflicts in the same folder you can add a number to the filenames e.g. `fullscreen-playback-of-switching-sets-manual-ToS_MultiRate_fragmented-ToS_HEAACv2_fragmented_1.html` and `fullscreen-playback-of-switching-sets-manual-ToS_MultiRate_fragmented-ToS_HEAACv2_fragmented_2.html`

**Comment by FritzHeiden** [comment]
@jpiesing I pushed the discussed changes. 6731bc939455cf77d63806787e4b137d1d0f4c92

**Comment by louaybassbouss** [comment]
Thanks @FritzHeiden LGTM
