### ISSUE TITLE
limitation of playout for splicing test

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#50]
Is there any limitation of playout parameter for splicing test? Or it will be robust that any values are allowed please?
To do correct observation we need to know whether or not there is any limitation to the playout for splicing test.
Because of the playout is not configured on TR by default, the user can enter anything without any allowed limit. 

With playout[i]: [(Switching Set, CMAF track number, Fragment number)]
Switching set: I think test runner only allow 1 or 2, @louaybassbouss can you confirm please? What if user enter anything other than 1 or 2? 
CMAF track number: this is always 1 from the example but can it be anything? Does switching within splicing allowed? 
Fragment number: is this always in order and covers whole duration or it allows any value?

Normal playout value:
```
playout = {
[ 1, 1, 1 ],
[ 1, 1, 2 ],
....
[ 1, 1, 20 ],
[ 2, 1, 1 ],
...
[ 2, 1, 15 ],
[ 1, 1, 21 ],
...
[ 1, 1, 30 ]
}
```

The following is one complicated example of the playout parameter:
Which contains random access, switching within splicing, out of order loading within same splicing, playback finishes early (not play whole duration), fragment jump (10 to 15 from ad), out or order across the splicing. 
I tried to come up with the most complex combination, but we would like to know if this is the valid test that OF need to support, please?
```
playout = {
[ 1, 1, 10 ],
[ 1, 1, 11 ],
[ 1, 1, 12 ],
[ 1, 1, 8 ],
[ 1, 1, 16 ],
[ 1, 1, 15 ],
[ 1, 1, 14 ],
[ 1, 1, 18 ],
[ 1, 1, 19 ],
[ 1, 1, 20 ],
[ 1, 1, 17 ],
[ 2, 1, 1 ],
[ 2, 1, 2 ],
[ 2, 2, 3 ],
[ 2, 2, 4 ],
[ 2, 3, 5 ],
[ 2, 3, 6 ],
[ 2, 4, 7 ],
[ 2, 4, 8 ],
[ 2, 5, 9 ],
[ 2, 5, 10 ],
[ 2, 5, 15 ],
[ 1, 1, 21 ],
[ 1, 1, 22 ],
[ 1, 1, 23 ],
[ 1, 1, 24 ],
[ 2, 1, 11 ],
[ 2, 1, 12 ],
[ 2, 1, 13 ],
[ 2, 1, 14 ],
[ 1, 1, 25 ],
[ 1, 1, 26 ],
[ 1, 1, 1 ],
}
```

**Comment by louaybassbouss** [comment]
> Is there any limitation of playout parameter for splicing test? Or it will be robust that any values are allowed please?
To do correct observation we need to know whether or not there is any limitation to the playout for splicing test.
Because of the playout is not configured on TR by default, the user can enter anything without any allowed limit.

@yanj-github I prefer to provide a default value for `playout` in [test-config.json](https://github.com/cta-wave/dpctf-tests/blob/master/test-config.json). It can be overwritten with user defined value. Basically the core test player support any number of switching sets for example if you provide in the CSV 3 Video MPDs for the same test, then you can use `1`, `2` and `3` as switching set index in the `playout` array. 

> With playout[i]: [(Switching Set, CMAF track number, Fragment number)]
Switching set: I think test runner only allow 1 or 2, @louaybassbouss can you confirm please? What if user enter anything other than 1 or 2?
CMAF track number: this is always 1 from the example but can it be anything? Does switching within splicing allowed?
Fragment number: is this always in order and covers whole duration or it allows any value?

Regarding CMAF Track number is same situation. If you have multiple representations in the MPD, then you can use the index of the representation you want to use in the test. In Splicing Test is most probably `1` since we are not switching between CMAF tracks. But in general, switching between CMAF Tracks within splicing is supported. 

> The following is one complicated example of the playout parameter:
Which contains random access, switching within splicing, out of order loading within same splicing, playback finishes early (not play whole duration), fragment jump (10 to 15 from ad), out or order across the splicing.
I tried to come up with the most complex combination, but we would like to know if this is the valid test that OF need to support, please?

We didn't tested all these combination but in general it should work. Why is this important for you? We should make sure that the combinations required for the DPCTF tests are working properly. We can investigate more on this if you see issues with combinations required for the tests.

**Comment by jpiesing** [comment]
> Is there any limitation of playout parameter for splicing test? Or it will be robust that any values are allowed please?
> To do correct observation we need to know whether or not there is any limitation to the playout for splicing test.
> Because of the playout is not configured on TR by default, the user can enter anything without any allowed limit.

Users should not be configuring anything at all.
All properties & values **need** to have sensible defaults.
I don't believe any effort should be spent on making the test runner or OF robust if users change the default configurations - all bets are off if they do something stupid. In fact we should probably document that we don't provide any support on this.

**Comment by yanj-github** [comment]
Thanks @jpiesing  and @louaybassbouss. 
I think it will be better to made an agreement between providing default playout parameter on test code level or for each and every test in the configuration. There is a risk in defaulting on test code level it might not work on different content depands on which content the test code is mapped with. Or fix the playout parameter for each and every test in the configuration so that user wont allowed to change. Any thoguht on this please?

**Comment by jpiesing** [comment]
I think this issue has now shrunk & become the same as [when playout parameter is missing](https://github.com/cta-wave/dpctf-tests/issues/49). If that's correct, please close this one. If it's not correct, please be clear about what is left here.

**Comment by yanj-github** [comment]
Missing playout paramter for splicing test is to be added, which will be managed in #49 
Based on `Users should not be configuring anything at all. `
OF will not support the any (random) playout that is changed by user.
